"""The colours, which are not magpie's to choose.

Noctalia regenerates `~/.config/hypr/noctalia.lua` from the wallpaper on every
change. The clipboard is part of this desktop, so it reads that file rather
than carrying a palette of its own.
"""

import pytest

from magpie.palette import DEFAULTS, Palette, darken, lighten, mix, read

LUA = '''-- Generated by Noctalia

local primary = "rgb(ffb2ba)"
local surface = "rgb(1a1112)"
local secondary = "rgb(f7b6bc)"
local error = "rgb(ffb4ab)"
'''

CONF = '''$primary = rgb(c2c6d6)
$surface = rgb(131314)
$secondary = rgb(c6c6cd)
$error = rgb(ffb4ab)
$tertiary = rgb(d6c0ce)
$surface_lowest = rgb(0e0e0f)
'''


def test_it_reads_the_lua_noctalia_writes(tmp_path):
    (tmp_path / "noctalia.lua").write_text(LUA)
    assert read(tmp_path).primary == "#ffb2ba"
    assert read(tmp_path).surface == "#1a1112"


def test_it_reads_the_conf_when_there_is_no_lua(tmp_path):
    (tmp_path / "noctalia.conf").write_text(CONF)
    assert read(tmp_path).primary == "#c2c6d6"


def test_the_lua_wins_when_both_are_there(tmp_path):
    # Noctalia writes both; the conf on this machine is months stale.
    (tmp_path / "noctalia.lua").write_text(LUA)
    (tmp_path / "noctalia.conf").write_text(CONF)
    assert read(tmp_path).primary == "#ffb2ba"


def test_nothing_to_read_is_not_a_crash(tmp_path):
    assert read(tmp_path) == DEFAULTS


def test_half_a_file_keeps_the_defaults_for_the_rest(tmp_path):
    (tmp_path / "noctalia.lua").write_text('local primary = "rgb(00ff00)"\n')
    palette = read(tmp_path)
    assert palette.primary == "#00ff00"
    assert palette.surface == DEFAULTS.surface


def test_a_file_full_of_nonsense_is_ignored(tmp_path):
    (tmp_path / "noctalia.lua").write_text("local primary = notacolour\n\x00\xff")
    assert read(tmp_path) == DEFAULTS


# -- mixing ------------------------------------------------------------------


def test_mixing_all_the_way_is_the_other_colour():
    assert mix("#000000", "#ffffff", 1.0) == "#ffffff"


def test_mixing_none_of_the_way_is_the_first():
    assert mix("#123456", "#ffffff", 0.0) == "#123456"


def test_halfway_is_halfway():
    assert mix("#000000", "#ffffff", 0.5) == "#808080"


def test_lightening_raises_every_channel():
    assert lighten("#101010", 0.5) > "#101010"


def test_darkening_lowers_it():
    assert darken("#808080", 0.5) == "#404040"


# -- what the window asks for ------------------------------------------------


@pytest.fixture
def dark():
    return Palette(primary="#ffb2ba", surface="#1a1112", secondary="#f7b6bc",
                   error="#ffb4ab", tertiary="#d6c0ce", surface_lowest="#0e0e0f")


def test_the_rail_is_below_the_list_and_the_pane_is_above_it(dark):
    # The window is three things side by side and should not read as one sheet.
    assert dark.rail < dark.ink < dark.pane


def test_the_text_is_light_on_a_dark_wallpaper(dark):
    assert dark.bone > "#c0c0c0"


def test_the_quiet_text_is_between_the_two(dark):
    assert dark.ink < dark.ash < dark.bone


def test_the_accent_is_the_wallpaper_colour(dark):
    assert dark.accent == dark.primary


@pytest.fixture
def light():
    return Palette(primary="#4a5a8a", surface="#f2f0ec", secondary="#8a8a90",
                   error="#ba1a1a", tertiary="#6a5a70", surface_lowest="#ffffff")


def test_a_light_wallpaper_turns_the_text_dark(light):
    assert light.bone < "#404040"
    assert light.rail > "#d0d0d0"


def test_every_role_is_a_colour_a_stylesheet_will_take(dark):
    import re

    for role in ("rail", "ink", "pane", "slate", "quill", "bone", "ash",
                 "accent", "danger", "edge"):
        assert re.fullmatch(r"#[0-9a-f]{6}", getattr(dark, role)), role


def test_the_scrim_is_dark_enough_to_read_a_glyph_on(dark):
    # It sits on top of a screenshot, which can be any colour at all, so it
    # cannot be derived from the wallpaper alone the way the panels are.
    assert dark.scrim < "#303030"


def test_the_scrim_is_dark_on_a_light_wallpaper_too(light):
    assert light.scrim < "#303030"
